Fix header files
json-parser/json-parser pull request #109
Opened 2021-08-07 08:52 UTC by DimitriPapadopoulos

**json.h**: `<inttypes.h>` → `<stdint.h>`
`int64_t` is defined in `<stdint.h>`, no need for the full `<inttypes.h>`

**json.h**: `<stdlib.h>` → `<stddef.h>`
`<stddef.h>` is enough to define `size_t`

**json.c**: `<stdlib.h>`
Now that `<stdlib.h>` has been removed from json.h, add it to json.c for malloc()/calloc() and free()

2021-08-10 07:08 UTC, DimitriPapadopoulos commented
Note that this patch does not change the status of the library regarding ANSI C vs. C89 compatibility:
* The additional `<stddef.h>` header is ANSI C.
* The ANSI C header `<stdlib.h>` is just moved around, from **json.h** to **json.c**.
* Neither `<inttypes.h>` nor `<stdint.h>` are ANSI C. Both are C99 and both are included only if `json_int_t` is not already defined, and additionally `<inttypes.h>` includes `<stdint.h>` anyway:
```
#ifndef json_int_t
   #ifndef _MSC_VER
      #include <inttypes.h>
```

2021-08-14 16:17 UTC, LB-- requested changes
Thanks! After doing some more thinking and research, perhaps it would be better to use a progressive-enhancement approach where we check the presence and value of [`__STDC_VERSION__`](https://en.cppreference.com/w/c/preprocessor/replace#Predefined_macros) to know what is safe to use. I think also we should stick to `long`/`long long`/`int_fast64_t` since `int64_t` and co are optional and not guaranteed to exist. Though, that might be better suited to a different commit, as there are more places than just here that use `int64_t`. The user can also override the default by defining `json_int_t`, which I hope to add proper documentation for later. Thoughts?

Also, would you like your name added to the `AUTHORS` file? You may add it yourself or I will add it for you, or you can opt-out, whichever you prefer.

2021-08-14 19:16 UTC, DimitriPapadopoulos commented
I agree about both:
* `checking __STDC_VERSION__` to introduce C99 headers for example,
* avoid `int64`, but on the other hand `int64` is used only if `json_int_t` is not defined.

However, I also agree the above ideas are orthogonal to the current patch, which is about using the proper header files without changing the status with respect to ANSI C or `int64`. I would rather see this pull request merged before working on the above ideas.

2021-08-14 20:00 UTC, LB-- commented
> without changing the status

Good point, I'll go ahead and merge this PR in that case. Yes or no to `AUTHORS` file?

2021-08-14 20:00 UTC, LB-- approved these changes

2021-08-14 20:04 UTC, DimitriPapadopoulos commented
I've submitted another PR for AUTHORS.

2021-08-14 20:34 UTC, merged