Variable `flags` is assigned a value that is never used
json-parser/json-parser pull request #157
Opened 2021-12-09 09:49 UTC by DimitriPapadopoulos

2026-09-04 00:04 UTC, LB-- requested changes
Is this to silence a warning? This doesn't affect optimized release codegen at all so I don't get the point. If there's some sort of warning about this we should find a better way to silence the warning, e.g. by initializing it to  `flag_seek_value` rather than leaving it uninitialized.

2026-09-06 18:34 UTC, DimitriPapadopoulos commented
Exactly, but I cannot recall which warning from which tool :grimacing:

2026-09-06 18:48 UTC, DimitriPapadopoulos commented
The variable `flags` is set to ` flag_seek_value` and used inside the `for` loop only if I'm not mistaken. Make it a variable local to the loop?

2026-09-06 18:55 UTC, DimitriPapadopoulos commented
Same for `top`?

2026-09-06 21:39 UTC, LB-- commented
Seems like `top` is used in the error path so it's best left alone for now. God idea moving the `flags` declaration into the loop body though, thanks!

2026-09-06 21:39 UTC, merged