Check for trailing garbage inside json
json-parser/json-parser pull request #80
Opened 2019-02-04 01:35 UTC by tmegow

A stab at addressing open issue #73

2021-08-07 02:11 UTC, LB-- requested changes
There are too many formatting/spacing changes that make it difficult to see the actual changed code. Would you be willing to try again without reformatting the source file?

2021-11-03 08:52 UTC, DimitriPapadopoulos commented
@tmegow Could you perhaps discard the [indentation](https://github.com/json-parser/json-parser/pull/80/commits/32524f513ca88e4467e71cf221a6c181c4015588) and [formatting](https://github.com/json-parser/json-parser/pull/80/commits/86d646c1290528e51a22bfd0857d7cc80898a719) commits? Then, commit [Allow for empty objects and empty arrays](https://github.com/json-parser/json-parser/pull/80/commits/d63b9d80a6053c66241468322ee314d6db303292) must be reworked to only bring essential changes.

I'm not saying the current format is perfect, but reformatting everything while adding actual changes is never an option.

2021-11-05 07:07 UTC, DimitriPapadopoulos commented on json.h
> +int trailing_garbage (const json_char *);
Does this function need to be declared in `json.h`? I don't think so, it should be a static function of `json.c`.

2021-11-05 07:11 UTC, DimitriPapadopoulos commented on json.c
> +        case 'e':
It looks like you're looking for `"false"` Perhaps a `strncmp()` would be more readable. At least add a comment, like `/* skipping "false" */` or something similar.

2021-11-05 07:12 UTC, DimitriPapadopoulos commented on json.c
> +                if (*(--ptr) == 'l' && *(--ptr) == 'a' && *(--ptr) == 'f')
Here you decrement `--ptr` multiple times. Are there cases where you could decrement pas the beginning of the buffer?

2021-11-05 07:13 UTC, DimitriPapadopoulos commented on json.c
> +            if (marker == 'u')
It looks like you're looking for "true" Perhaps a strncmp() would be more readable. At least add a comment, like /* skipping "true" */ or something similar.

2021-11-05 07:14 UTC, DimitriPapadopoulos commented on json.c
> +                if (*(--ptr) == 'r' && *(--ptr) == 't')
Same comment about multiple `--ptr`.

2021-11-05 07:15 UTC, DimitriPapadopoulos commented on json.c
> +        case 'l':
It looks like you're looking for `"null"` Perhaps a `strncmp()` would be more readable. At least add a comment, like `/* skipping "null" */` or something similar.

2021-11-05 07:15 UTC, DimitriPapadopoulos commented on json.c
> +            if (*(--ptr) == 'l' && *(--ptr) == 'u' && *(--ptr) == 'n')
Same comment about multiple `--ptr`.

2021-11-05 09:27 UTC, DimitriPapadopoulos commented on json.c
> +        case 'e':
But then would `strncmp()` work for all possible types of `json_char`?

2021-12-07 16:41 UTC, closed without merging